# Generated by Django 2.2.1 on 2019-10-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190919_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profesion',
            new_name='profession',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
