# Generated by Django 2.2.1 on 2019-10-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191017_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_in_months',
            field=models.SmallIntegerField(),
        ),
    ]
