# Generated by Django 2.2.1 on 2019-06-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(blank='True', upload_to='profiles'),
        ),
    ]
