# Generated by Django 2.2.1 on 2019-09-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_students_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='registeration_number',
            new_name='registration_number',
        ),
    ]
