# Generated by Django 2.2.1 on 2019-10-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190919_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='course.Course'),
        ),
    ]
